### ISSUE TITLE
License

### ISSUE THREAD

**Issue by syntagmatic** [mrmilosz/hypersolid#5]
I'm considering using hypersolid.js for a commercial installation.

@mrmilosz can we put an open-source license on this project?

**Comment by mrmilosz** [comment]
@syntagmatic sounds good. Let's give it an MIT license for maximum freedom. You are welcome to include the license yourself, unless you would like me to do it.

I still feel kind of bad that the rotation is weird and I never fixed it. Perhaps we should roll back to having rotation always relative to the previous cube state? But then there are theoretical floating point issues.... though those did seem to cancel out in some way because I've played with the old cube for hours and the points never seemed to get out of alignment. Hmm. Well that's my rant, what do you think?

**Comment by syntagmatic** [comment]
Okay, added the license at the top of  https://github.com/mrmilosz/hypersolid/blob/master/hypersolid.js

I'll open a new issue for the rotations.
